/**
 * This class is generated by jOOQ
 */
package com.clicdirectory;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.clicdirectory.tables.records.MemberRecord, java.lang.Long> IDENTITY_MEMBER = Identities0.IDENTITY_MEMBER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.clicdirectory.tables.records.MemberRecord> MEMBER_PKEY = UniqueKeys0.MEMBER_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.clicdirectory.tables.records.MemberRecord, java.lang.Long> IDENTITY_MEMBER = createIdentity(com.clicdirectory.tables.Member.MEMBER, com.clicdirectory.tables.Member.MEMBER.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.clicdirectory.tables.records.MemberRecord> MEMBER_PKEY = createUniqueKey(com.clicdirectory.tables.Member.MEMBER, com.clicdirectory.tables.Member.MEMBER.EMAIL);
	}
}
