/**
 * This class is generated by jOOQ
 */
package com.clicdirectory;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -563580266;

	/**
	 * The singleton instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			com.clicdirectory.Sequences.MEMBER_ID_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.clicdirectory.tables.Groupdata.GROUPDATA,
			com.clicdirectory.tables.Gutable.GUTABLE,
			com.clicdirectory.tables.Member.MEMBER,
			com.clicdirectory.tables.Messagestack.MESSAGESTACK,
			com.clicdirectory.tables.Pgtable.PGTABLE,
			com.clicdirectory.tables.Posttable.POSTTABLE,
			com.clicdirectory.tables.Test.TEST,
			com.clicdirectory.tables.Userdata.USERDATA,
			com.clicdirectory.tables.Whatsapp.WHATSAPP);
	}
}
