/**
 * This class is generated by jOOQ
 */
package com.clicdirectory;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.Groupdata
	 */
	public static final com.clicdirectory.tables.Groupdata GROUPDATA = com.clicdirectory.tables.Groupdata.GROUPDATA;

	/**
	 * The table public.GUtable
	 */
	public static final com.clicdirectory.tables.Gutable GUTABLE = com.clicdirectory.tables.Gutable.GUTABLE;

	/**
	 * The table public.member
	 */
	public static final com.clicdirectory.tables.Member MEMBER = com.clicdirectory.tables.Member.MEMBER;

	/**
	 * The table public.Messagestack
	 */
	public static final com.clicdirectory.tables.Messagestack MESSAGESTACK = com.clicdirectory.tables.Messagestack.MESSAGESTACK;

	/**
	 * The table public.PGtable
	 */
	public static final com.clicdirectory.tables.Pgtable PGTABLE = com.clicdirectory.tables.Pgtable.PGTABLE;

	/**
	 * The table public.PostTable
	 */
	public static final com.clicdirectory.tables.Posttable POSTTABLE = com.clicdirectory.tables.Posttable.POSTTABLE;

	/**
	 * The table public.Test
	 */
	public static final com.clicdirectory.tables.Test TEST = com.clicdirectory.tables.Test.TEST;

	/**
	 * The table public.Userdata
	 */
	public static final com.clicdirectory.tables.Userdata USERDATA = com.clicdirectory.tables.Userdata.USERDATA;

	/**
	 * The table public.whatsapp
	 */
	public static final com.clicdirectory.tables.Whatsapp WHATSAPP = com.clicdirectory.tables.Whatsapp.WHATSAPP;
}
