/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gutable extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.GutableRecord> {

	private static final long serialVersionUID = 922558178;

	/**
	 * The singleton instance of <code>public.GUtable</code>
	 */
	public static final com.clicdirectory.tables.Gutable GUTABLE = new com.clicdirectory.tables.Gutable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.GutableRecord> getRecordType() {
		return com.clicdirectory.tables.records.GutableRecord.class;
	}

	/**
	 * The column <code>public.GUtable.Group1</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.GutableRecord, java.lang.String> GROUP1 = createField("Group1", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.GUtable.User</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.GutableRecord, java.lang.Long> USER = createField("User", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.GUtable.Task</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.GutableRecord, java.lang.Long> TASK = createField("Task", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.GUtable.Post</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.GutableRecord, java.lang.Long> POST = createField("Post", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.GUtable</code> table reference
	 */
	public Gutable() {
		this("GUtable", null);
	}

	/**
	 * Create an aliased <code>public.GUtable</code> table reference
	 */
	public Gutable(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Gutable.GUTABLE);
	}

	private Gutable(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.GutableRecord> aliased) {
		this(alias, aliased, null);
	}

	private Gutable(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.GutableRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Gutable as(java.lang.String alias) {
		return new com.clicdirectory.tables.Gutable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Gutable rename(java.lang.String name) {
		return new com.clicdirectory.tables.Gutable(name, null);
	}
}
