/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Messagestack extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.MessagestackRecord> {

	private static final long serialVersionUID = -838720199;

	/**
	 * The singleton instance of <code>public.Messagestack</code>
	 */
	public static final com.clicdirectory.tables.Messagestack MESSAGESTACK = new com.clicdirectory.tables.Messagestack();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.MessagestackRecord> getRecordType() {
		return com.clicdirectory.tables.records.MessagestackRecord.class;
	}

	/**
	 * The column <code>public.Messagestack.message</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MessagestackRecord, java.lang.String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Messagestack.tag</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MessagestackRecord, java.lang.String> TAG = createField("tag", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Messagestack.status</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MessagestackRecord, java.lang.Long> STATUS = createField("status", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.Messagestack.tstamp</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MessagestackRecord, java.lang.Long> TSTAMP = createField("tstamp", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.Messagestack.contactno</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MessagestackRecord, java.lang.String> CONTACTNO = createField("contactno", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.Messagestack</code> table reference
	 */
	public Messagestack() {
		this("Messagestack", null);
	}

	/**
	 * Create an aliased <code>public.Messagestack</code> table reference
	 */
	public Messagestack(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Messagestack.MESSAGESTACK);
	}

	private Messagestack(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.MessagestackRecord> aliased) {
		this(alias, aliased, null);
	}

	private Messagestack(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.MessagestackRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Messagestack as(java.lang.String alias) {
		return new com.clicdirectory.tables.Messagestack(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Messagestack rename(java.lang.String name) {
		return new com.clicdirectory.tables.Messagestack(name, null);
	}
}
