/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Posttable extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.PosttableRecord> {

	private static final long serialVersionUID = -825561707;

	/**
	 * The singleton instance of <code>public.PostTable</code>
	 */
	public static final com.clicdirectory.tables.Posttable POSTTABLE = new com.clicdirectory.tables.Posttable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.PosttableRecord> getRecordType() {
		return com.clicdirectory.tables.records.PosttableRecord.class;
	}

	/**
	 * The column <code>public.PostTable.post_content</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.PosttableRecord, java.lang.String> POST_CONTENT = createField("post_content", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.PostTable.post_id</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.PosttableRecord, java.lang.Long> POST_ID = createField("post_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.PostTable.post_tag</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.PosttableRecord, java.lang.String> POST_TAG = createField("post_tag", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.PostTable</code> table reference
	 */
	public Posttable() {
		this("PostTable", null);
	}

	/**
	 * Create an aliased <code>public.PostTable</code> table reference
	 */
	public Posttable(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Posttable.POSTTABLE);
	}

	private Posttable(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.PosttableRecord> aliased) {
		this(alias, aliased, null);
	}

	private Posttable(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.PosttableRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Posttable as(java.lang.String alias) {
		return new com.clicdirectory.tables.Posttable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Posttable rename(java.lang.String name) {
		return new com.clicdirectory.tables.Posttable(name, null);
	}
}
