/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userdata extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.UserdataRecord> {

	private static final long serialVersionUID = 665670113;

	/**
	 * The singleton instance of <code>public.Userdata</code>
	 */
	public static final com.clicdirectory.tables.Userdata USERDATA = new com.clicdirectory.tables.Userdata();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.UserdataRecord> getRecordType() {
		return com.clicdirectory.tables.records.UserdataRecord.class;
	}

	/**
	 * The column <code>public.Userdata.contactno</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.UserdataRecord, java.lang.Long> CONTACTNO = createField("contactno", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.Userdata.password</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.UserdataRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Userdata.usertype</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.UserdataRecord, java.lang.String> USERTYPE = createField("usertype", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Userdata.authentication</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.UserdataRecord, java.lang.Long> AUTHENTICATION = createField("authentication", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.Userdata.email</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.UserdataRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.Userdata</code> table reference
	 */
	public Userdata() {
		this("Userdata", null);
	}

	/**
	 * Create an aliased <code>public.Userdata</code> table reference
	 */
	public Userdata(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Userdata.USERDATA);
	}

	private Userdata(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.UserdataRecord> aliased) {
		this(alias, aliased, null);
	}

	private Userdata(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.UserdataRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Userdata as(java.lang.String alias) {
		return new com.clicdirectory.tables.Userdata(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Userdata rename(java.lang.String name) {
		return new com.clicdirectory.tables.Userdata(name, null);
	}
}
