/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Whatsapp extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.WhatsappRecord> {

	private static final long serialVersionUID = 1233046708;

	/**
	 * The singleton instance of <code>public.whatsapp</code>
	 */
	public static final com.clicdirectory.tables.Whatsapp WHATSAPP = new com.clicdirectory.tables.Whatsapp();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.WhatsappRecord> getRecordType() {
		return com.clicdirectory.tables.records.WhatsappRecord.class;
	}

	/**
	 * The column <code>public.whatsapp.IDno</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.WhatsappRecord, java.lang.Long> IDNO = createField("IDno", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.whatsapp.Status</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.WhatsappRecord, java.lang.Long> STATUS = createField("Status", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.whatsapp.BoxNo</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.WhatsappRecord, java.lang.Long> BOXNO = createField("BoxNo", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.whatsapp</code> table reference
	 */
	public Whatsapp() {
		this("whatsapp", null);
	}

	/**
	 * Create an aliased <code>public.whatsapp</code> table reference
	 */
	public Whatsapp(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Whatsapp.WHATSAPP);
	}

	private Whatsapp(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.WhatsappRecord> aliased) {
		this(alias, aliased, null);
	}

	private Whatsapp(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.WhatsappRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Whatsapp as(java.lang.String alias) {
		return new com.clicdirectory.tables.Whatsapp(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Whatsapp rename(java.lang.String name) {
		return new com.clicdirectory.tables.Whatsapp(name, null);
	}
}
