/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GutableRecord extends org.jooq.impl.TableRecordImpl<com.clicdirectory.tables.records.GutableRecord> implements org.jooq.Record4<java.lang.String, java.lang.Long, java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 1390427772;

	/**
	 * Setter for <code>public.GUtable.Group1</code>.
	 */
	public void setGroup1(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.GUtable.Group1</code>.
	 */
	public java.lang.String getGroup1() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.GUtable.User</code>.
	 */
	public void setUser(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.GUtable.User</code>.
	 */
	public java.lang.Long getUser() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>public.GUtable.Task</code>.
	 */
	public void setTask(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.GUtable.Task</code>.
	 */
	public java.lang.Long getTask() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>public.GUtable.Post</code>.
	 */
	public void setPost(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.GUtable.Post</code>.
	 */
	public java.lang.Long getPost() {
		return (java.lang.Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.Long, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.Long, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.clicdirectory.tables.Gutable.GUTABLE.GROUP1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.clicdirectory.tables.Gutable.GUTABLE.USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.clicdirectory.tables.Gutable.GUTABLE.TASK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.clicdirectory.tables.Gutable.GUTABLE.POST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getGroup1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getTask();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getPost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GutableRecord value1(java.lang.String value) {
		setGroup1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GutableRecord value2(java.lang.Long value) {
		setUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GutableRecord value3(java.lang.Long value) {
		setTask(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GutableRecord value4(java.lang.Long value) {
		setPost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GutableRecord values(java.lang.String value1, java.lang.Long value2, java.lang.Long value3, java.lang.Long value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GutableRecord
	 */
	public GutableRecord() {
		super(com.clicdirectory.tables.Gutable.GUTABLE);
	}

	/**
	 * Create a detached, initialised GutableRecord
	 */
	public GutableRecord(java.lang.String group1, java.lang.Long user, java.lang.Long task, java.lang.Long post) {
		super(com.clicdirectory.tables.Gutable.GUTABLE);

		setValue(0, group1);
		setValue(1, user);
		setValue(2, task);
		setValue(3, post);
	}
}
