/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRecord extends org.jooq.impl.UpdatableRecordImpl<com.clicdirectory.tables.records.MemberRecord> implements org.jooq.Record11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1993588296;

	/**
	 * Setter for <code>public.member.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.member.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.member.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.member.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.member.phone</code>.
	 */
	public void setPhone(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.member.phone</code>.
	 */
	public java.lang.String getPhone() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.member.location</code>.
	 */
	public void setLocation(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.member.location</code>.
	 */
	public java.lang.String getLocation() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.member.is_verified</code>.
	 */
	public void setIsVerified(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.member.is_verified</code>.
	 */
	public java.lang.Boolean getIsVerified() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>public.member.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.member.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.member.role</code>.
	 */
	public void setRole(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.member.role</code>.
	 */
	public java.lang.String getRole() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.member.token</code>.
	 */
	public void setToken(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.member.token</code>.
	 */
	public java.lang.String getToken() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.member.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.member.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(8);
	}

	/**
	 * Setter for <code>public.member.fb_token</code>.
	 */
	public void setFbToken(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.member.fb_token</code>.
	 */
	public java.lang.String getFbToken() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>public.member.authentication</code>.
	 */
	public void setAuthentication(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.member.authentication</code>.
	 */
	public java.lang.String getAuthentication() {
		return (java.lang.String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.clicdirectory.tables.Member.MEMBER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.clicdirectory.tables.Member.MEMBER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.clicdirectory.tables.Member.MEMBER.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.clicdirectory.tables.Member.MEMBER.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return com.clicdirectory.tables.Member.MEMBER.IS_VERIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.clicdirectory.tables.Member.MEMBER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.clicdirectory.tables.Member.MEMBER.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.clicdirectory.tables.Member.MEMBER.TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return com.clicdirectory.tables.Member.MEMBER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.clicdirectory.tables.Member.MEMBER.FB_TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.clicdirectory.tables.Member.MEMBER.AUTHENTICATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getIsVerified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getFbToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getAuthentication();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value1(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value2(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value3(java.lang.String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value4(java.lang.String value) {
		setLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value5(java.lang.Boolean value) {
		setIsVerified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value6(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value7(java.lang.String value) {
		setRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value8(java.lang.String value) {
		setToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value9(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value10(java.lang.String value) {
		setFbToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value11(java.lang.String value) {
		setAuthentication(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Boolean value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.Long value9, java.lang.String value10, java.lang.String value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MemberRecord
	 */
	public MemberRecord() {
		super(com.clicdirectory.tables.Member.MEMBER);
	}

	/**
	 * Create a detached, initialised MemberRecord
	 */
	public MemberRecord(java.lang.String name, java.lang.String email, java.lang.String phone, java.lang.String location, java.lang.Boolean isVerified, java.lang.String password, java.lang.String role, java.lang.String token, java.lang.Long id, java.lang.String fbToken, java.lang.String authentication) {
		super(com.clicdirectory.tables.Member.MEMBER);

		setValue(0, name);
		setValue(1, email);
		setValue(2, phone);
		setValue(3, location);
		setValue(4, isVerified);
		setValue(5, password);
		setValue(6, role);
		setValue(7, token);
		setValue(8, id);
		setValue(9, fbToken);
		setValue(10, authentication);
	}
}
