/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagestackRecord extends org.jooq.impl.TableRecordImpl<com.clicdirectory.tables.records.MessagestackRecord> implements org.jooq.Record5<java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String> {

	private static final long serialVersionUID = 709649139;

	/**
	 * Setter for <code>public.Messagestack.message</code>.
	 */
	public void setMessage(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.Messagestack.message</code>.
	 */
	public java.lang.String getMessage() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.Messagestack.tag</code>.
	 */
	public void setTag(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.Messagestack.tag</code>.
	 */
	public java.lang.String getTag() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.Messagestack.status</code>.
	 */
	public void setStatus(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.Messagestack.status</code>.
	 */
	public java.lang.Long getStatus() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>public.Messagestack.tstamp</code>.
	 */
	public void setTstamp(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.Messagestack.tstamp</code>.
	 */
	public java.lang.Long getTstamp() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>public.Messagestack.contactno</code>.
	 */
	public void setContactno(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.Messagestack.contactno</code>.
	 */
	public java.lang.String getContactno() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.clicdirectory.tables.Messagestack.MESSAGESTACK.MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.clicdirectory.tables.Messagestack.MESSAGESTACK.TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.clicdirectory.tables.Messagestack.MESSAGESTACK.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.clicdirectory.tables.Messagestack.MESSAGESTACK.TSTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.clicdirectory.tables.Messagestack.MESSAGESTACK.CONTACTNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getTstamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getContactno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagestackRecord value1(java.lang.String value) {
		setMessage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagestackRecord value2(java.lang.String value) {
		setTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagestackRecord value3(java.lang.Long value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagestackRecord value4(java.lang.Long value) {
		setTstamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagestackRecord value5(java.lang.String value) {
		setContactno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagestackRecord values(java.lang.String value1, java.lang.String value2, java.lang.Long value3, java.lang.Long value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MessagestackRecord
	 */
	public MessagestackRecord() {
		super(com.clicdirectory.tables.Messagestack.MESSAGESTACK);
	}

	/**
	 * Create a detached, initialised MessagestackRecord
	 */
	public MessagestackRecord(java.lang.String message, java.lang.String tag, java.lang.Long status, java.lang.Long tstamp, java.lang.String contactno) {
		super(com.clicdirectory.tables.Messagestack.MESSAGESTACK);

		setValue(0, message);
		setValue(1, tag);
		setValue(2, status);
		setValue(3, tstamp);
		setValue(4, contactno);
	}
}
