/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PosttableRecord extends org.jooq.impl.TableRecordImpl<com.clicdirectory.tables.records.PosttableRecord> implements org.jooq.Record3<java.lang.String, java.lang.Long, java.lang.String> {

	private static final long serialVersionUID = -588157765;

	/**
	 * Setter for <code>public.PostTable.post_content</code>.
	 */
	public void setPostContent(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.PostTable.post_content</code>.
	 */
	public java.lang.String getPostContent() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.PostTable.post_id</code>.
	 */
	public void setPostId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.PostTable.post_id</code>.
	 */
	public java.lang.Long getPostId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>public.PostTable.post_tag</code>.
	 */
	public void setPostTag(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.PostTable.post_tag</code>.
	 */
	public java.lang.String getPostTag() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.clicdirectory.tables.Posttable.POSTTABLE.POST_CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.clicdirectory.tables.Posttable.POSTTABLE.POST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.clicdirectory.tables.Posttable.POSTTABLE.POST_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getPostContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getPostId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPostTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PosttableRecord value1(java.lang.String value) {
		setPostContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PosttableRecord value2(java.lang.Long value) {
		setPostId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PosttableRecord value3(java.lang.String value) {
		setPostTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PosttableRecord values(java.lang.String value1, java.lang.Long value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PosttableRecord
	 */
	public PosttableRecord() {
		super(com.clicdirectory.tables.Posttable.POSTTABLE);
	}

	/**
	 * Create a detached, initialised PosttableRecord
	 */
	public PosttableRecord(java.lang.String postContent, java.lang.Long postId, java.lang.String postTag) {
		super(com.clicdirectory.tables.Posttable.POSTTABLE);

		setValue(0, postContent);
		setValue(1, postId);
		setValue(2, postTag);
	}
}
