/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WhatsappRecord extends org.jooq.impl.TableRecordImpl<com.clicdirectory.tables.records.WhatsappRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 2101232006;

	/**
	 * Setter for <code>public.whatsapp.IDno</code>.
	 */
	public void setIdno(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.whatsapp.IDno</code>.
	 */
	public java.lang.Long getIdno() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.whatsapp.Status</code>.
	 */
	public void setStatus(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.whatsapp.Status</code>.
	 */
	public java.lang.Long getStatus() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>public.whatsapp.BoxNo</code>.
	 */
	public void setBoxno(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.whatsapp.BoxNo</code>.
	 */
	public java.lang.Long getBoxno() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.clicdirectory.tables.Whatsapp.WHATSAPP.IDNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.clicdirectory.tables.Whatsapp.WHATSAPP.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.clicdirectory.tables.Whatsapp.WHATSAPP.BOXNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getIdno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getBoxno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WhatsappRecord value1(java.lang.Long value) {
		setIdno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WhatsappRecord value2(java.lang.Long value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WhatsappRecord value3(java.lang.Long value) {
		setBoxno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WhatsappRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WhatsappRecord
	 */
	public WhatsappRecord() {
		super(com.clicdirectory.tables.Whatsapp.WHATSAPP);
	}

	/**
	 * Create a detached, initialised WhatsappRecord
	 */
	public WhatsappRecord(java.lang.Long idno, java.lang.Long status, java.lang.Long boxno) {
		super(com.clicdirectory.tables.Whatsapp.WHATSAPP);

		setValue(0, idno);
		setValue(1, status);
		setValue(2, boxno);
	}
}
